User choose color - Jimmy Vu
Jimmy-Vu/final-project pull request #8
Opened 2021-11-09 18:11 UTC by Jimmy-Vu

https://user-images.githubusercontent.com/88172055/140980536-af6b2bc6-9982-4dbc-87bf-f86a1f6d0e3e.mov

https://user-images.githubusercontent.com/88172055/140980550-2a366d09-ec03-4e35-9f3f-d18f0a20b8b9.mov

2021-11-09 18:28 UTC, thebearingedge approved these changes

2021-11-12 18:52 UTC, Jimmy-Vu commented
![Screen Shot 2021-11-12 at 10 46 31 AM](https://user-images.githubusercontent.com/88172055/141519791-27621a7f-2e7e-49c0-9dc9-d0679f2d849f.png)

2021-11-12 19:01 UTC, thebearingedge requested changes

2021-11-12 19:01 UTC, thebearingedge commented on server/public/index.html
> +    </script> -->
You can remove this.

2021-11-12 19:12 UTC, merged